apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-docker-k8s
  template:
    metadata:
      labels:
        app: spring-docker-k8s
    spec:
      containers:
        - name: spring-docker-k8s
          image: hemkant/github-actions
          ports:
            - containerPort: 5678